package com.tiva11.navigationtut;

import androidx.appcompat.app.AppCompatActivity;
import androidx.databinding.DataBindingUtil;
import androidx.lifecycle.Observer;
import androidx.lifecycle.ViewModelProviders;
import androidx.navigation.NavController;
import androidx.navigation.NavDirections;
import androidx.navigation.Navigation;
import androidx.navigation.fragment.NavHostFragment;

import android.net.Uri;
import android.os.Bundle;
import android.util.Log;

import com.tiva11.navigationtut.databinding.ActivityMainBinding;

public class MainActivity extends AppCompatActivity implements MainFragment.OnFragmentInteractionListener, ConfirmationFragment.OnFragmentInteractionListener {
    private static final String TAG = "MainActivity";
    private ActivityMainBinding binding;
    private AppMainViewModel viewModel;
    private NavController navController;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        //setContentView(R.layout.activity_main); //THis was the default generated by the New Project Wizard
        binding = DataBindingUtil.setContentView(this, R.layout.activity_main);
        viewModel = ViewModelProviders.of(this).get(AppMainViewModel.class);
        binding.setLifecycleOwner(this);
//        navController = ((NavHostFragment) getSupportFragmentManager()
//                .findFragmentById(R.id.nav_host_fragment))
//                .getNavController();
        navController = Navigation.findNavController(this,R.id.nav_host_fragment);
        viewModel.getNewDestination().observe(this, new Observer<NavDirections>() {
            @Override
            public void onChanged(NavDirections destination) {
                Log.i(TAG, "onChanged: " + destination);
                navController.navigate(destination);
            }
        });
    }
    @Override
    public void onFragmentInteraction(Uri uri) {
        Log.i(TAG, "onFragmentInteraction: " + uri);
    }
}

